version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    container_name: nginx
    # extra_hosts:
    #   - "host.docker.internal:host-gateway" 
    ports:
      - "8093:80"
      - "8496:443"
    volumes:
      - ./../.:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - laravel_app
    hostname: laravel_app.test

  mysql:
    image: mariadb:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4311:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_DATABASE: laravel_app
      MARIADB_USER: laravel_app
      MARIADB_PASSWORD: laravel_app
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    networks:
      - laravel_app

  php:
    build:
      context: .
      dockerfile: DockerfilePhp
    container_name: php
    volumes:
      - ./../.:/var/www/html
      - ./supervisor/laravel_app.conf:/etc/supervisor.d/laravel_app.ini
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./run.sh:/var/www/html/run.sh
    ports:
      - "9013:9000"
    networks:
      - laravel_app

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass 123456
    container_name: redis
    ports:
      - "6392:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - laravel_app

volumes:
  mysql:
    external: true
  nginx:
    external: true
  redis:
    external: true 

networks:
  laravel_app:
    external: true
    # driver: bridge